name: Create Release Notes Draft

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release-note-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main
      - name: Check should create release note
        id: check
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" && \
                "${{ startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/') }}" == "true" && \
                "${{ github.base_ref }}" == "main" ]]; then
            echo "should_create_release_note=true" >> $GITHUB_OUTPUT
            VERSION=$(echo ${{ github.head_ref }} | cut -d '/' -f 2)
            echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "should_create_release_note=false" >> $GITHUB_OUTPUT
          fi
      - name: create Release Note Draft
        if: steps.check.outputs.should_create_release_note == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION_TAG=${{ steps.check.outputs.tag_name }}
          gh release create ${VERSION_TAG} \
            --target main \
            --title "v${VERSION_TAG}リリース" \
            --generate-notes \
            --draft \
            --latest
