name: Create Release Notes

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check-should-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Check should run
        id: check-should-run
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" && \
                "${{ startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/') }}" == "true" && \
                "${{ github.base_ref }}" == "main" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            VERSION=$(echo ${{ github.head_ref }} | cut -d '/' -f 2)
            echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
      - name: create Release Note Draft
        if: steps.check-should-run.outputs.should_run == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION_TAG=${{ steps.check-should-run.outputs.tag_name }}
          gh release create ${VERSION_TAG} \
            --target main \
            --title "v${VERSION_TAG}リリース" \
            --generate-notes \
            --draft \
            --latest
